brew "git-lfs"
brew "httpie"
brew "jq"
brew "tree"

cask "fork"
cask "visual-studio-code"
cask "spotify"
cask "discord"
cask "telegram"
cask "xcodes"

tap "homebrew/cask-fonts"
cask "font-jetbrains-mono"
